// <auto-generated />
using System;
using Shared.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Shared.Persistence.Migrations{
    [DbContext(typeof(CruisesDbContext))]
    [Migration("20260223232636_Bookings")]
    partial class Bookings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CruiseDateId")
                        .HasColumnType("integer");

                    b.Property<int>("PaymenId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CruiseDateId");

                    b.HasIndex("PaymenId")
                        .IsUnique();

                    b.ToTable("Bookings", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.BookingCabin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<int>("CabinId")
                        .HasColumnType("integer");

                    b.Property<int>("Occupants")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("CabinId");

                    b.ToTable("BookingCabins", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.BookingCabinOccupant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BookingCabinId")
                        .HasColumnType("integer");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingCabinId");

                    b.ToTable("BookingCabinOccupants", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.BookingExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<int>("ExtraId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ExtraId");

                    b.ToTable("BookingExtras", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.BookingPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BookingPayment", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.CabinType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CabinTypes", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.Cruise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowsMinors")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("integer");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean");

                    b.Property<string>("Itinerary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginPort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AllowsMinors");

                    b.HasIndex("OriginPort");

                    b.HasIndex("Zone");

                    b.ToTable("Cruises", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.CruiseDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CruiseId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceModifier")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ShipId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CruiseId");

                    b.HasIndex("ShipId");

                    b.ToTable("CruiseDates", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.CruiseDateExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CruiseDateId")
                        .HasColumnType("integer");

                    b.Property<int>("ExtraId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CruiseDateId");

                    b.HasIndex("ExtraId");

                    b.ToTable("CruiseDateExtras", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.Extra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.ToTable("Extras", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ships", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.ShipCabin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ShipId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CabinTypeId");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipCabins", "dbo");
                });

            modelBuilder.Entity("Domain.Entities.Booking", b =>
                {
                    b.HasOne("Domain.Entities.CruiseDate", "CruiseDate")
                        .WithMany("Bookings")
                        .HasForeignKey("CruiseDateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.BookingPayment", "Payment")
                        .WithOne("Booking")
                        .HasForeignKey("Domain.Entities.Booking", "PaymenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CruiseDate");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Domain.Entities.BookingCabin", b =>
                {
                    b.HasOne("Domain.Entities.Booking", "Booking")
                        .WithMany("Cabins")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ShipCabin", "Cabin")
                        .WithMany("BookingCabins")
                        .HasForeignKey("CabinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Cabin");
                });

            modelBuilder.Entity("Domain.Entities.BookingCabinOccupant", b =>
                {
                    b.HasOne("Domain.Entities.BookingCabin", "BookingCabin")
                        .WithMany("OccupantsDetails")
                        .HasForeignKey("BookingCabinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookingCabin");
                });

            modelBuilder.Entity("Domain.Entities.BookingExtra", b =>
                {
                    b.HasOne("Domain.Entities.Booking", "Booking")
                        .WithMany("Extras")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Extra", "Extra")
                        .WithMany("BookingCabinExtras")
                        .HasForeignKey("ExtraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Extra");
                });

            modelBuilder.Entity("Domain.Entities.CruiseDate", b =>
                {
                    b.HasOne("Domain.Entities.Cruise", "Cruise")
                        .WithMany("CruiseDates")
                        .HasForeignKey("CruiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Ship", "Ship")
                        .WithMany("CruiseDates")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cruise");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("Domain.Entities.CruiseDateExtra", b =>
                {
                    b.HasOne("Domain.Entities.CruiseDate", "CruiseDate")
                        .WithMany("CruiseDateExtras")
                        .HasForeignKey("CruiseDateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Extra", "Extra")
                        .WithMany("CruiseDateExtras")
                        .HasForeignKey("ExtraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CruiseDate");

                    b.Navigation("Extra");
                });

            modelBuilder.Entity("Domain.Entities.ShipCabin", b =>
                {
                    b.HasOne("Domain.Entities.CabinType", "CabinType")
                        .WithMany("ShipCabins")
                        .HasForeignKey("CabinTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Ship", "Ship")
                        .WithMany("Cabins")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CabinType");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("Domain.Entities.Booking", b =>
                {
                    b.Navigation("Cabins");

                    b.Navigation("Extras");
                });

            modelBuilder.Entity("Domain.Entities.BookingCabin", b =>
                {
                    b.Navigation("OccupantsDetails");
                });

            modelBuilder.Entity("Domain.Entities.BookingPayment", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Domain.Entities.CabinType", b =>
                {
                    b.Navigation("ShipCabins");
                });

            modelBuilder.Entity("Domain.Entities.Cruise", b =>
                {
                    b.Navigation("CruiseDates");
                });

            modelBuilder.Entity("Domain.Entities.CruiseDate", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CruiseDateExtras");
                });

            modelBuilder.Entity("Domain.Entities.Extra", b =>
                {
                    b.Navigation("BookingCabinExtras");

                    b.Navigation("CruiseDateExtras");
                });

            modelBuilder.Entity("Domain.Entities.Ship", b =>
                {
                    b.Navigation("Cabins");

                    b.Navigation("CruiseDates");
                });

            modelBuilder.Entity("Domain.Entities.ShipCabin", b =>
                {
                    b.Navigation("BookingCabins");
                });
#pragma warning restore 612, 618
        }
    }
}
