// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shared.Persistence;

#nullable disable

namespace Shared.Persistence.Migrations
{
    [DbContext(typeof(CruisesDbContext))]
    [Migration("20260723213143_RemoveLockedCabinNumber")]
    partial class RemoveLockedCabinNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Shared.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChargeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("ChargeId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ChargedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CheckInTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CruiseDateId")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("integer");

                    b.Property<string>("PaymentTokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RefundId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CheckInTokenHash")
                        .IsUnique();

                    b.HasIndex("CruiseDateId");

                    b.HasIndex("PaymentTokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Bookings", "dbo");
                });

            modelBuilder.Entity("Shared.Domain.Entities.BookingCabin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<int>("CabinId")
                        .HasColumnType("integer");

                    b.Property<int>("Occupants")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("CabinId");

                    b.ToTable("BookingCabins", "dbo");
                });

            modelBuilder.Entity("Shared.Domain.Entities.BookingCabinOccupant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BookingCabinId")
                        .HasColumnType("integer");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingCabinId");

                    b.ToTable("BookingCabinOccupants", "dbo");
                });

            modelBuilder.Entity("Shared.Domain.Entities.BookingExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<int>("ExtraId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ExtraId");

                    b.ToTable("BookingExtras", "dbo");
                });

            modelBuilder.Entity("Shared.Domain.Entities.CabinType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CabinTypes", "dbo");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Cruise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdultsOnly")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("integer");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean");

                    b.Property<string>("Itinerary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginPort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdultsOnly");

                    b.HasIndex("OriginPort");

                    b.HasIndex("Zone");

                    b.ToTable("Cruises", "dbo");
                });

            modelBuilder.Entity("Shared.Domain.Entities.CruiseDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CruiseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaymentStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PriceModifier")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ShipId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CruiseId");

                    b.HasIndex("ShipId");

                    b.ToTable("CruiseDates", "dbo");
                });

            modelBuilder.Entity("Shared.Domain.Entities.CruiseDateExtra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CruiseDateId")
                        .HasColumnType("integer");

                    b.Property<int>("ExtraId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CruiseDateId");

                    b.HasIndex("ExtraId");

                    b.ToTable("CruiseDateExtras", "dbo");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Extra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.ToTable("Extras", "dbo");
                });

            modelBuilder.Entity("Shared.Domain.Entities.LockedCabin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinId")
                        .HasColumnType("integer");

                    b.Property<int>("CruiseDateId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBookingInProgress")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CabinId");

                    b.HasIndex("CruiseDateId");

                    b.HasIndex("UserId");

                    b.ToTable("LockedCabins", "dbo");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ships", "dbo");
                });

            modelBuilder.Entity("Shared.Domain.Entities.ShipCabin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ShipId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CabinTypeId");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipCabins", "dbo");
                });

            modelBuilder.Entity("Shared.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("KeycloakUserGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("Shared.Domain.Entities.UserPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("CardBrand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardHolderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpirationMonth")
                        .HasColumnType("integer");

                    b.Property<int>("ExpirationYear")
                        .HasColumnType("integer");

                    b.Property<string>("LastFourDigits")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Active")
                        .IsUnique()
                        .HasFilter("\"Active\" = true");

                    b.ToTable("PaymentMethods", "dbo");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Booking", b =>
                {
                    b.HasOne("Shared.Domain.Entities.CruiseDate", "CruiseDate")
                        .WithMany("Bookings")
                        .HasForeignKey("CruiseDateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shared.Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CruiseDate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Domain.Entities.BookingCabin", b =>
                {
                    b.HasOne("Shared.Domain.Entities.Booking", "Booking")
                        .WithMany("Cabins")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shared.Domain.Entities.ShipCabin", "Cabin")
                        .WithMany("BookingCabins")
                        .HasForeignKey("CabinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Cabin");
                });

            modelBuilder.Entity("Shared.Domain.Entities.BookingCabinOccupant", b =>
                {
                    b.HasOne("Shared.Domain.Entities.BookingCabin", "BookingCabin")
                        .WithMany("OccupantsDetails")
                        .HasForeignKey("BookingCabinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BookingCabin");
                });

            modelBuilder.Entity("Shared.Domain.Entities.BookingExtra", b =>
                {
                    b.HasOne("Shared.Domain.Entities.Booking", "Booking")
                        .WithMany("Extras")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shared.Domain.Entities.Extra", "Extra")
                        .WithMany("BookingCabinExtras")
                        .HasForeignKey("ExtraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Extra");
                });

            modelBuilder.Entity("Shared.Domain.Entities.CruiseDate", b =>
                {
                    b.HasOne("Shared.Domain.Entities.Cruise", "Cruise")
                        .WithMany("CruiseDates")
                        .HasForeignKey("CruiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shared.Domain.Entities.Ship", "Ship")
                        .WithMany("CruiseDates")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cruise");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("Shared.Domain.Entities.CruiseDateExtra", b =>
                {
                    b.HasOne("Shared.Domain.Entities.CruiseDate", "CruiseDate")
                        .WithMany("CruiseDateExtras")
                        .HasForeignKey("CruiseDateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shared.Domain.Entities.Extra", "Extra")
                        .WithMany("CruiseDateExtras")
                        .HasForeignKey("ExtraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CruiseDate");

                    b.Navigation("Extra");
                });

            modelBuilder.Entity("Shared.Domain.Entities.LockedCabin", b =>
                {
                    b.HasOne("Shared.Domain.Entities.ShipCabin", "Cabin")
                        .WithMany()
                        .HasForeignKey("CabinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shared.Domain.Entities.CruiseDate", "CruiseDate")
                        .WithMany()
                        .HasForeignKey("CruiseDateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shared.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cabin");

                    b.Navigation("CruiseDate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Domain.Entities.ShipCabin", b =>
                {
                    b.HasOne("Shared.Domain.Entities.CabinType", "CabinType")
                        .WithMany("ShipCabins")
                        .HasForeignKey("CabinTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shared.Domain.Entities.Ship", "Ship")
                        .WithMany("Cabins")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CabinType");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("Shared.Domain.Entities.User", b =>
                {
                    b.OwnsOne("Shared.Domain.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("Locality")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Address_Locality");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Address_PostalCode");

                            b1.Property<string>("Region")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Address_Region");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Address_Street");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", "dbo");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Domain.Entities.UserPayment", b =>
                {
                    b.HasOne("Shared.Domain.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Cabins");

                    b.Navigation("Extras");
                });

            modelBuilder.Entity("Shared.Domain.Entities.BookingCabin", b =>
                {
                    b.Navigation("OccupantsDetails");
                });

            modelBuilder.Entity("Shared.Domain.Entities.CabinType", b =>
                {
                    b.Navigation("ShipCabins");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Cruise", b =>
                {
                    b.Navigation("CruiseDates");
                });

            modelBuilder.Entity("Shared.Domain.Entities.CruiseDate", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CruiseDateExtras");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Extra", b =>
                {
                    b.Navigation("BookingCabinExtras");

                    b.Navigation("CruiseDateExtras");
                });

            modelBuilder.Entity("Shared.Domain.Entities.Ship", b =>
                {
                    b.Navigation("Cabins");

                    b.Navigation("CruiseDates");
                });

            modelBuilder.Entity("Shared.Domain.Entities.ShipCabin", b =>
                {
                    b.Navigation("BookingCabins");
                });

            modelBuilder.Entity("Shared.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
