//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Agents.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Agents.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud de aprobación de la herramienta {0} no corresponde al tipo {1} esperado por el manejador..
        /// </summary>
        public static string ApprovalRequestTypeMismatch {
            get {
                return ResourceManager.GetString("ApprovalRequestTypeMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Se ha producido un error que impide continuar con la conversación..
        /// </summary>
        public static string ChatStreamFailed {
            get {
                return ResourceManager.GetString("ChatStreamFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No tiene permiso para acceder a esta conversación..
        /// </summary>
        public static string SessionAccessDenied {
            get {
                return ResourceManager.GetString("SessionAccessDenied", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a La sesión de conversación no contiene mensajes..
        /// </summary>
        public static string SessionHasNoMessages {
            get {
                return ResourceManager.GetString("SessionHasNoMessages", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El Id de sesión no coincide con la sesión almacenada..
        /// </summary>
        public static string SessionIdMismatch {
            get {
                return ResourceManager.GetString("SessionIdMismatch", resourceCulture);
            }
        }
    }
}
