//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Application.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La reserva ya está cancelada.
        /// </summary>
        public static string BookingAlreadyCanceled {
            get {
                return ResourceManager.GetString("BookingAlreadyCanceled", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a La reserva ya está pagada..
        /// </summary>
        public static string BookingAlreadyPaid {
            get {
                return ResourceManager.GetString("BookingAlreadyPaid", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a La reserva está cancelada y no puede pagarse..
        /// </summary>
        public static string BookingCanceledCannotPay {
            get {
                return ResourceManager.GetString("BookingCanceledCannotPay", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No se puede cancelar una reserva pagada cuyo check-in ya ha comenzado..
        /// </summary>
        public static string BookingCheckInAlreadyStarted {
            get {
                return ResourceManager.GetString("BookingCheckInAlreadyStarted", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No existe la reserva {0}.
        /// </summary>
        public static string BookingNotFound {
            get {
                return ResourceManager.GetString("BookingNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a La reserva no está pendiente de pago..
        /// </summary>
        public static string BookingNotPendingPayment {
            get {
                return ResourceManager.GetString("BookingNotPendingPayment", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a La reserva {0} no existe..
        /// </summary>
        public static string BookingNotFoundInWorkflow {
            get {
                return ResourceManager.GetString("BookingNotFoundInWorkflow", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a La reserva no existe o no pertenece al usuario..
        /// </summary>
        public static string BookingNotFoundOrNotOwned {
            get {
                return ResourceManager.GetString("BookingNotFoundOrNotOwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La reserva está pendiente de pago.
        /// </summary>
        public static string BookingPaymentPending {
            get {
                return ResourceManager.GetString("BookingPaymentPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El camarote ya tiene registrados sus {0} pasajero(s) reservados..
        /// </summary>
        public static string CabinBookedOccupancyReached {
            get {
                return ResourceManager.GetString("CabinBookedOccupancyReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El camarote no pertenece a la reserva..
        /// </summary>
        public static string CabinNotInBooking {
            get {
                return ResourceManager.GetString("CabinNotInBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El check-in ya no está disponible para esta reserva..
        /// </summary>
        public static string CheckInNoLongerAvailable {
            get {
                return ResourceManager.GetString("CheckInNoLongerAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El check-in de esta reserva todavía no está disponible. Podrás realizarlo a partir del {0}..
        /// </summary>
        public static string CheckInNotStarted {
            get {
                return ResourceManager.GetString("CheckInNotStarted", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No existe ningún check-in pendiente para ese enlace..
        /// </summary>
        public static string CheckInTokenNotFound {
            get {
                return ResourceManager.GetString("CheckInTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya hay un pasajero con el DNI &apos;{0}&apos; en la reserva..
        /// </summary>
        public static string DuplicatePassengerDni {
            get {
                return ResourceManager.GetString("DuplicatePassengerDni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Faltan pasajeros por registrar en alguno de los camarotes.
        /// </summary>
        public static string MissingPassengers {
            get {
                return ResourceManager.GetString("MissingPassengers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No handler registered for {0}.
        /// </summary>
        public static string NoHandlerRegistered {
            get {
                return ResourceManager.GetString("NoHandlerRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de nacimiento del pasajero no es válida..
        /// </summary>
        public static string PassengerBirthDateInvalid {
            get {
                return ResourceManager.GetString("PassengerBirthDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los campos del pasajero son obligatorios..
        /// </summary>
        public static string PassengerFieldsRequired {
            get {
                return ResourceManager.GetString("PassengerFieldsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El pasajero no pertenece a la reserva..
        /// </summary>
        public static string PassengerNotInBooking {
            get {
                return ResourceManager.GetString("PassengerNotInBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no tiene una ficha de cliente en la pasarela de pago..
        /// </summary>
        public static string PaymentCustomerMissing {
            get {
                return ResourceManager.GetString("PaymentCustomerMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Error al procesar el pago..
        /// </summary>
        public static string PaymentFailed {
            get {
                return ResourceManager.GetString("PaymentFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No puede borrar un medio de pago que forme parte de una reserva activa.
        /// </summary>
        public static string PaymentMethodInUse {
            get {
                return ResourceManager.GetString("PaymentMethodInUse", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Debe indicarse un método de pago..
        /// </summary>
        public static string PaymentMethodRequired {
            get {
                return ResourceManager.GetString("PaymentMethodRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Los camarotes elegidos no estan disponibles o han expirado.
        /// </summary>
        public static string CabinNotAvailable {
            get {
                return ResourceManager.GetString("CabinNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al procesar el reembolso.
        /// </summary>
        public static string RefundFailed {
            get {
                return ResourceManager.GetString("RefundFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido calcular el impuesto.
        /// </summary>
        public static string TaxCalculationFailed {
            get {
                return ResourceManager.GetString("TaxCalculationFailed", resourceCulture);
            }
        }
    }
}
