<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8baf4055-57f6-478d-b84d-18d826137ee6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup Condition="'$(ImplicitUsings)' == 'enable'">
    <Using Include="Core.Api" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="invoices\**" />
    <Content Remove="invoices\**" />
    <EmbeddedResource Remove="invoices\**" />
    <None Remove="invoices\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Carter" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.6" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\aspire\ServiceDefaults\ServiceDefaults.csproj" />
    <ProjectReference Include="..\Agents\Core.Agents.csproj" />
    <ProjectReference Include="..\Application\Core.Application.csproj" />
    <ProjectReference Include="..\Infraestructure\Core.Infrastructure.csproj" />
  </ItemGroup>

</Project>
