<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapr.Jobs" Version="1.18.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
	 <PackageReference Include="PDFsharp-MigraDoc" Version="6.2.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Domain\Shared.Domain.csproj" />
  </ItemGroup>

</Project>
