apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: jobs-pub-sub
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    secretKeyRef:
      name: RABBITMQ_CONNECTION_STRING
      key: RABBITMQ_CONNECTION_STRING
  - name: durable
    value: "false"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: reconnectWait
    value: "5"
  - name: concurrency
    value: parallel
auth:
  secretStore: kubernetes
